# Generated by Django 5.1.7 on 2025-04-28 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitypost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitypost',
            name='author',
            field=models.ForeignKey(help_text='User who authored this post', on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who have joined this group', related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='created_by',
            field=models.ForeignKey(help_text='User who organized this hackathon', on_delete=django.db.models.deletion.CASCADE, related_name='hackathons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(help_text='User who posted this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='posted_by',
            field=models.ForeignKey(help_text='User who shared this resource', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningresource',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for categorization', max_length=255),
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Progress percentage (0-100)'),
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='user',
            field=models.ForeignKey(help_text='User whose progress is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
