# Generated by Django 5.1.7 on 2025-03-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created_at_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
